import type { Metadata } from "next";
import { Geist } from "@/ui/fonts";
import "./globals.css";

import { Providers } from "@/components/providers";
// import { AppProvider } from "@/context/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Geist.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
